# Generated by Django 3.2.3 on 2022-01-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220126_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
