# Generated by Django 3.2.3 on 2022-02-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20220207_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='docfile',
            field=models.FileField(null='True', upload_to='upload_to', verbose_name='file'),
            preserve_default='True',
        ),
    ]
